name: "Rust publish workflow"

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
      build-dependencies:
        type: string
        required: false
    secrets:
      CRATES_TOKEN:
        required: true

jobs:

  publish:
    name: publish
    if: ${{ github.event_name == 'push' &&
            startsWith(github.ref, 'refs/tag') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install build-dependencies
        if: inputs.build-dependencies != ''
        run: |
          sudo apt install ${{ inputs.build-dependencies }}
      - name: determine package
        if: inputs.package != ''
        run: |
          echo "PACKAGE_ARG=-p ${{ inputs.package }}" >>"$GITHUB_ENV"
      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_TOKEN }} ${{ env.PACKAGE_ARG }}
