name: "Rust test workflow"

on:
  workflow_call:
    inputs:
      toolchain:
        type: string
        required: true
      args:
        type: string
        required: true
      build-dependencies:
        type: string
        required: false
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:

  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - name: audit
        run: |
          cargo audit --color always --deny warnings

  test:
    name: test
    needs: [audit]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: llvm-tools-preview
      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: install build-dependencies
        if: inputs.build-dependencies != ''
        run: |
          sudo apt install ${{ inputs.build-dependencies }}
      - name: run tests
        run: |
          cargo llvm-cov \
              --all-features \
              --lcov \
              --output-path coverage.lcov \
              ${{ inputs.args }}
      - name: upload coverage data
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          fail_ci_if_error: true
          name: ${{ format('{0} {1}', inputs.toolchain, inputs.args) }}
